#!/usr/bin/env python3
import sys

name=sys.argv[1] 
color=sys.argv[2]
activity=sys.argv[3]
animal=sys.argv[4]
#now print a message on the screen
print('melissa likes', name,'and',color,'and',activity,'and',animal)

